version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install SAM CLI
      - pip install --user aws-sam-cli
      - export PATH=$PATH:$HOME/.local/bin

      # Install frontend dependencies
      - cd src && npm ci && cd ..

  build:
    commands:
      # Build frontend (Vite)
      - echo "Building frontend..."
      - cd src && npm run build && cd ..
     

      # Build backend (SAM)
      - echo "Building backend..."
      - |
        if [ -d "backend" ]; then
          cd backend && sam build --use-container;
        else
          echo "Error: backend directory missing";
          exit 1;
        fi
  post_build:
    commands:
       # Package SAM app (Note: Current directory is 'backend' at this point)
      - | # Check for template.yaml in the current directory
        if [ -f "template.yaml" ]; then
          sam package --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged.yaml --region eu-west-2;
        else
          echo "Error: template.yaml missing";
          exit 1;
        fi

      # Deploy frontend to S3
      - cd .. 
      - aws s3 sync dist s3://$FRONTEND_BUCKET --delete

artifacts:
  files:
    - backend/packaged.yaml
    - backend/template.yaml
    - dist/**/*
  base-directory: .

cache:
  paths:
    # Cache frontend node modules relative to the source directory
    - 'src/node_modules/**/*'