version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Debug directory structure
      - echo "Contents of $CODEBUILD_SRC_DIR:"
      - ls -la
      
      # Frontend install
      - cd src && npm ci && cd ..

  build:
    commands:
      # Frontend build with error handling
      - echo "Building frontend..."
      - cd src && (npm run build || (echo "Build failed. Contents:" && ls -la)) && cd ..
      - mv src/dist public

      # Backend build (only if directory exists)
      - if [ ! -d "backend" ]; then echo "ERROR: backend/ missing"; exit 1; fi
      - cd backend && sam build --use-container && cd ..

  post_build:
    commands:
      # Package backend with validation
      - pwd && ls -la
      - if [ -f "backend/template.yaml" ]; then
          cd backend && sam package \
            --s3-bucket $ARTIFACT_BUCKET \
            --output-template-file packaged.yaml;
        else
          echo "ERROR: template.yaml missing";
          exit 1;
        fi

      # Frontend deploy
      - aws s3 sync public s3://$FRONTEND_BUCKET --delete

artifacts:
  files:
    - backend/packaged.yaml
    - backend/template.yaml
    - public/**/*